audio-optio/Controllers/CheckoutsController.cs
using Braintree;

using System;
using System.Collections.Generic;
using System.Web.Mvc;

using audio_optio.Database;
using audio_optio.Models;
using audio_optio.Services;

namespace audio_optio.Controllers
{
    public class CheckoutsController : Controller
    {
        private IEmailService emailService_;
        private AddressRepository addressRepo_;

        public CheckoutsController(IEmailService emailService)
        {
            AoDbContext context = new AoDbContext();
            addressRepo_ = new AddressRepository(context);

            emailService_ = emailService;
        }


        public ActionResult Update(PaymentModel model)
        {
            return View("Create", model);
        }

        [HttpPost]
        public ActionResult Create(PaymentModel model)
        {
            // Gateway token in view
            var gateway = audio_optio.App_Data.Configuration.GetGateway();
            var nonce = Request["payment_method_nonce"];

            model.Format();
            foreach (String error in model.Validate())
            {
                ModelState.AddModelError("error", error);
            }
            
            if (ModelState.IsValid)
            {
                // Save addresses
                model.contactOrder.order.ShippingAddress.Contact = model.contactOrder.contact;
                model.contactOrder.order.BillingAddress.Contact = model.contactOrder.contact;
                addressRepo_.Insert(model.contactOrder.order.ShippingAddress);
                addressRepo_.Insert(model.contactOrder.order.BillingAddress);
            }
            else
            {
                // Recreate gateway token for view 
                var clientToken = gateway.ClientToken.Generate();
                ViewBag.ClientToken = clientToken;
                return View("Pay", model);
            }

            var request = new TransactionRequest
            {
                Amount = Convert.ToDecimal(model.Price),
                PaymentMethodNonce = nonce,
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true
                },
                BillingAddress = new AddressRequest
                {
                    FirstName = model.contactOrder.order.BillingAddress.To,
                    StreetAddress = model.contactOrder.order.BillingAddress.AddressLine1,
                    ExtendedAddress = model.contactOrder.order.BillingAddress.AddressLine2,
                    PostalCode = model.contactOrder.order.BillingAddress.PostalCode,
                    CountryCodeAlpha2 = "US"
                },
                Customer = new CustomerRequest
                {
                    FirstName = model.contactOrder.contact.FirstName,
                    LastName = model.contactOrder.contact.LastName,
                    Email = model.contactOrder.contact.Email,
                    Phone = model.contactOrder.contact.Phone
                },
                ShippingAddress = new AddressRequest
                {
                    FirstName = model.contactOrder.order.ShippingAddress.To,
                    StreetAddress = model.contactOrder.order.ShippingAddress.AddressLine1,
                    ExtendedAddress = model.contactOrder.order.ShippingAddress.AddressLine2,
                    PostalCode = model.contactOrder.order.ShippingAddress.PostalCode,
                    CountryCodeAlpha2 = "US"
                },
                OrderId = model.contactOrder.order.Id.ToString()
            };

            Result<Transaction> result = gateway.Transaction.Sale(request);
            if (result.IsSuccess())
            {
                Transaction transaction = result.Target;

                // Send notification
                emailService_.SendOrderEmail(model);

                return RedirectToAction("ShowDetails", new { id = transaction.Id });

            }
            else if (result.Transaction != null)
            {
                return RedirectToAction("ShowDetails", new { id = result.Transaction.Id });
            }
            else
            {
                List<String> errorMessages = new List<String>();

                foreach (ValidationError error in result.Errors.DeepAll())
                {
                    errorMessages.Add("Error: " + (int)error.Code + " - " + error.Message);
                }
                TempData["Flash"] = errorMessages;
                return View("FailView", errorMessages);
            }
        }

        public ActionResult ShowDetails(String id)
        {
            var gateway = audio_optio.App_Data.Configuration.GetGateway();
            Transaction transaction = gateway.Transaction.Find(id);


            ViewBag.Transaction = transaction;
            return View();
        }
    }
}

audio-optio/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Net.Mail;
using System.Text;
using System.Web.Mvc;

using audio_optio.App_Data;
using audio_optio.Domain;
using audio_optio.Models;
using audio_optio.Database;

using PayPal.Api;

using Address = audio_optio.Domain.Address;
using Order = audio_optio.Domain.Order;

namespace audio_optio.Controllers
{
    public class OrderController : Controller
    {
        private const string discountCode = "black20friday";
        private string orderEmail = Configuration.EmailCredentials.Email;
        private string pw = Configuration.EmailCredentials.Password;

        private ContactRepository contacts;
        private OrderRepository orders;

        public OrderController()
        {
            AoDbContext context = new AoDbContext();
            contacts = new ContactRepository(context);
            orders = new OrderRepository(context);
        }


        public ActionResult Order()
        {
            ContactOrderModel m = new ContactOrderModel();

            return View(m);
        }


        public ActionResult Checkout()
        {
            ContactOrderModel m = new ContactOrderModel();

            return View(m);
        }

        // GET: Order
        public ActionResult Index()
        {
            return View(orders.Get() as List<Order>);
        }

        // GET: Order/Details/5
        [Route("Order/Details/{id}")]
        public ActionResult Details(int id)
        {
            Order order = orders.Get(id);

            if(order == null)
            {
                return RedirectToAction("Order");
            }

            return View(order);
        }

        // POST: Order/Create
        [HttpPost]
        public ActionResult Create(ContactOrderModel model)
        {
            model.success = false;

            if (ModelState.IsValid)
            {
                model.contact.Format();
                
                if (!String.IsNullOrEmpty(model.order.DiscountCode) && !model.order.DiscountCode.ToLower().Equals(discountCode))
                {
                    model.success = false;
                    ModelState.AddModelError("Discount Code", "Discount code is invalid or expired.");
                    return View("Order", model);
                }

                model.success = true;

                Contact c = contacts.Get(model.contact.FirstName, model.contact.LastName);
                if (c == null)
                {
                    c = model.contact;
                    contacts.Insert(c);
                }

                contacts.Update(c);

                model.order.Contact = c;
                model.order.DateSubmitted = DateTime.Now;
                orders.Insert(model.order);
                
                return CreatePayment(model);
            }
            else
            {
                model.success = false;
                return Update(model);
            }
        }

        public ActionResult Update(ContactOrderModel model)
        {
            return View("Order", model);
        }


        public ActionResult CreatePayment(ContactOrderModel contactOrder)
        {
            PaymentModel m = new PaymentModel { contactOrder = contactOrder };
            m.Price = m.contactOrder == null ? 0.0m : audio_optio.Domain.Order.GetPrice(m.contactOrder.order.Size);
            
            // Evaluate discount code
            if (!String.IsNullOrEmpty(contactOrder.order.DiscountCode) && contactOrder.order.DiscountCode.ToLower().Equals(discountCode))
            {
                m.discountApplied = true;
                m.Price *= .8m;
            }

            m.contactOrder.order.OrderStatus = audio_optio.Domain.Order.Status.Pending;

            // Braintree gateway
            var gateway = Configuration.GetGateway();
            var clientToken = gateway.ClientToken.Generate();
            ViewBag.ClientToken = clientToken;
            
            return View("Pay", m);
        }
    }
}

audio-optio/Views/Order/Details.cshtml
@model audio_optio.Domain.Order

<h1>Order Details</h1>

<div class="row">
    <div class="col-lg-12 alert alert-success">
        Thank you for your order!  
        Your details have been submitted and payment was successful.  
        Ryan will be in contact with you shortly.
    </div>
</div>

<h2>Contact Information</h2>
<div class="row">
    <div class="col-lg-3">Name </div>
    <div class="col-lg-6">@Model.Contact.FirstName @Model.Contact.LastName</div>
</div>
<div class="row">
    <div class="col-lg-3">Email </div>
    <div class="col-lg-6">@Model.Contact.Email</div>
</div>

<div class="row">
    <div class="col-lg-3">Phone Number </div>
    <div class="col-lg-6">@Model.Contact.Phone</div>
</div>

<hr />
<h2>Order Information</h2>
<div class="row">
    <div class="col-lg-3">Song</div>
    <div class="col-lg-6">@Model.Song</div>
</div>
<div class="row">
    <div class="col-lg-3">Comments </div>
    <div class="col-lg-6">@Model.Comments</div>
</div>

<div class="row">
    <div class="col-lg-3">Date Submitted</div>
    <div class="col-lg-6">@Model.OrderStatus.ToString() </div>
</div>

<div class="row">
    <div class="col-lg-3">Date Submitted</div>
    <div class="col-lg-6">@Model.DateSubmitted.ToString() </div>
</div>

audio-optio/Views/Order/FailureView.cshtml
<div class="jumbotron alert alert-danger">
    <h2>Oops!</h2>

    Something went wrong...
</div>


@if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
{
    <div class="alert alert-danger" role="alert">
        <a class="close" data-dismiss="alert">×</a>
        @foreach (ModelError modelError in Html.ViewData.ModelState.SelectMany(keyValuePair => keyValuePair.Value.Errors))
        {
            <p>@modelError.ErrorMessage</p>
        }
    </div>
}

audio-optio/Views/Order/Index.cshtml
@using audio_optio.Domain
@model List<Order>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="table-responsive">
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <td>Name</td>
            <td></td>
            <td>Date Submitted</td>
            <td>Youtube Link</td>
            <td>Comments</td>
            <td>Order Type</td>
            <td>Status</td>
        </tr>
    </thead>

    @foreach (Order order in Model)
    {
        <tr>
            <td>@order.Contact.FirstName @order.Contact.LastName</td>
            <td></td>
            <td>@order.DateSubmitted</td>
            <td>@order.Song</td>
            <td>@order.Comments</td>
            <td>@Order.GetDescription(@order.Size)</td>
            <td>@order.OrderStatus</td>
        </tr>
    }

    <div class="table-responsive">
</table>

audio-optio/Views/Order/Order.cshtml
@model audio_optio.Models.ContactOrderModel

@{
    ViewBag.Title = "Order";
}

<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>

<style>
    .popover-title {
    font-size: 20px;
    font-family:'Lobster-Regular';
}
.popover-content {
    font-size: 15px;
    max-width:50% !important;
}

span
{
    display:inline-block;
    cursor:pointer;
    color:#008B8B;
    transition:ease-in .5s;
    font-size:20px;
}

span:hover
{
    color:black;
    transition:ease-in .5s;
}

.modal-header
{
    font-family:'Lobster-Regular';
    font-size:30px;
}


</style>


<div style="display:inline-block" class="emphasize">@ViewBag.Title</div>
         
<span class="glyphicon glyphicon-info-sign"  data-toggle="modal" data-target="#myModal"></span>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">How to Order</h4>
            </div>
            <div class="modal-body">
                <p>In order to start the process of ordering, you'll need to send some important information including:</p>
                <ul>
                    <li>a link to your favorite song on YouTube,</li>
                    <li>your preferred color theme,</li>
                    <li>desired canvas size,</li>
                    <li>and any general comments that will help me to create artwork that is perfect for you!</li>
                </ul>

                <p>I will contact you as soon as I receive and review your order to discuss further and to deliver three samples.</p>
                <p>Depending on print shop supply and demand, you should receive your canvas within 2-3 weeks of ordering!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>


@using (Html.BeginForm("Create", "Order", FormMethod.Post))
{
    if (@Model.success)
    {
        <div class="row">
            <div class="col-lg-12 alert alert-success">
                Thank you!  Your order has been submitted.  Ryan will be in touch with you shortly.
            </div>
        </div>

    }

    if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
    {
        <div class="alert alert-danger" role="alert">
            <a class="close" data-dismiss="alert">×</a>
            @foreach (ModelError modelError in Html.ViewData.ModelState.SelectMany(keyValuePair => keyValuePair.Value.Errors))
            {
                <p>@modelError.ErrorMessage</p>
            }
        </div>
    }

    <div class="row">
        <div class="col-md-3">@Html.Label("First Name")</div>
        <div class="col-md-9">@Html.TextBoxFor(c => c.contact.FirstName, new { @class = "form-control" })</div>
    </div>

    <div class="row">
        <div class="col-md-3">@Html.Label("Last Name")</div>
        <div class="col-md-9">@Html.TextBoxFor(c => c.contact.LastName, new { @class = "form-control" })</div>
    </div>

    <div class="row">
        <div class="col-md-3">@Html.Label("Phone Number")</div>
        <div class="col-md-9">@Html.TextBoxFor(c => c.contact.Phone, new { @class = "form-control" })</div>
    </div>

    <div class="row">
        <div class="col-md-3">@Html.Label("E-mail Address")</div>
        <div class="col-md-9">@Html.TextBoxFor(c => c.contact.Email, new { @class = "form-control" })</div>
    </div>

    <div class="row">
        <div class="col-md-3">@Html.Label("Song Name and Artist")</div>
        <div class="col-md-9">@Html.TextBoxFor(c => c.order.Song, new { @class = "form-control" })</div>
    </div>

    <div class="row">
        <div class="col-md-3">@Html.Label("Comments")</div>
        <div class="col-md-9">@Html.TextAreaFor(c => c.order.Comments, new { @class = "form-control", @rows = 10 })</div>
    </div>

    <div class="row">
        <div class="col-md-3">@Html.Label("Order Type")</div>
        <div class="col-md-9">@Html.DropDownListFor(m => m.order.Size, @Model.dropDownLabels, new { @class = "form-control" })</div>
    </div>

    <div class="row">
        <div class="col-md-3">@Html.Label("Discount Code")</div>
        <div class="col-md-9">@Html.TextBoxFor(c => c.order.DiscountCode, new { @class = "form-control" })</div>
    </div>
    
    <div class="row">
        <div class="col-md-2 col-md-offset-5">
            <input class="transition-button" type="submit" value="Continue to Payment" />
        </div>
    </div>
}

audio-optio/Views/Order/Pay.cshtml
@using audio_optio.Domain;
@model audio_optio.Models.PaymentModel

<style>
    label {
        font-weight: bold;
    }

    .simple-checkbox {
        outline: none;
        border: none !important;
        -webkit-box-shadow: none !important;
        -moz-box-shadow: none !important;
        box-shadow: none !important;
        width: 30px;
        height: 30px;
    }

    .animate-show-hide.ng-hide {
        opacity: 0;
    }

    .animate-show-hide.ng-hide-add,
    .animate-show-hide.ng-hide-remove {
        transition: all linear 0.5s;
    }

    a
    {
        cursor:pointer;
    }
    a:hover
    {
        text-decoration:none;
    }
    
</style>

@using (Html.BeginForm("Create", "Checkouts", FormMethod.Post, new { id = "payment-form" }))
{
    if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
    {
        <div class="alert alert-danger" role="alert">
            <a class="close" data-dismiss="alert">×</a>
            @foreach (ModelError modelError in Html.ViewData.ModelState.SelectMany(keyValuePair => keyValuePair.Value.Errors))
            {
                <p>@modelError.ErrorMessage</p>
            }
        </div>
    }

    <div>
        <h2>Order Information</h2>
        @Html.HiddenFor(m => m.contactOrder.contact.Id)
        @Html.HiddenFor(m => m.contactOrder.order.Id)
        <div class="row">
            <div class="col-md-3">@Html.Label("Name")</div>
            <div class="col-md-9">@Model.contactOrder.contact.FirstName @Model.contactOrder.contact.LastName</div>
            @Html.HiddenFor(m => m.contactOrder.contact.FirstName)
            @Html.HiddenFor(m => m.contactOrder.contact.LastName)
        </div>

        <div class="row">
            <div class="col-md-3">@Html.Label("E-mail Address")</div>
            <div class="col-md-9">@Model.contactOrder.contact.Email</div>
            @Html.HiddenFor(m => m.contactOrder.contact.Email)
        </div>

        <div class="row">
            <div class="col-md-3">@Html.Label("Phone Number")</div>
            <div class="col-md-9">@Model.contactOrder.contact.Phone</div>
            @Html.HiddenFor(m => m.contactOrder.contact.Phone)
        </div>

        <div class="row">
            <div class="col-md-3">@Html.Label("Song")</div>
            <div class="col-md-9">@Model.contactOrder.order.Song.ToString()</div>
            @Html.HiddenFor(m => m.contactOrder.order.Song)
        </div>

        <div class="row">
            <div class="col-md-3">@Html.Label("Comments")</div>
            <div class="col-md-9">@Model.contactOrder.order.Comments</div>
            @Html.HiddenFor(m => m.contactOrder.order.Comments)
        </div>

        <div class="row">
            <div class="col-md-3">@Html.Label("Date")</div>
            <div class="col-md-9">@Model.contactOrder.order.DateSubmitted.ToString("MM/dd/yyyy")</div>
            @Html.HiddenFor(m => m.contactOrder.order.DateSubmitted)
        </div>

        <div class="row">
            <div class="col-md-3">@Html.Label("Order Type")</div>
            <div class="col-md-9">@Order.GetDescription(@Model.contactOrder.order.Size)</div>
            @Html.HiddenFor(m => m.contactOrder.order.Size)
        </div>

        <div class="row">
            <div class="col-md-3">@Html.Label("Order Total")</div>
            <div class="col-md-9">$@Model.Price USD</div>
            @Html.HiddenFor(m => m.Price)
        </div>

        @if (Model.discountApplied)
        {
            <div class="row">
                <div class="col-md-12 alert alert-success">
                    30% discount applied!
                </div>
            </div>
        }

    </div>

    <hr />

    <div id="billing_address">
        <h2>Billing Address</h2>
        <div class="row">
            <div class="col-md-3"><label>Name</label></div>
            <div class="col-md-9">
                @Html.TextBoxFor(model => model.contactOrder.order.BillingAddress.To, new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-3"><label>Address Line 1</label></div>
            <div class="col-md-9">
                @Html.TextBoxFor(model => model.contactOrder.order.BillingAddress.AddressLine1, new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-3"><label>Address Line 2</label></div>
            <div class="col-md-9">
                @Html.TextBoxFor(model => model.contactOrder.order.BillingAddress.AddressLine2, new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-1"><label>City</label></div>
            <div class="col-md-2">
                @Html.TextBoxFor(model => model.contactOrder.order.BillingAddress.City, new { @class = "form-control" })
            </div>
            <div class="col-md-1"><label>State</label></div>
            <div class="col-md-2">
                @Html.DropDownListFor(model => model.contactOrder.order.BillingAddress.State,
               Enum.GetValues(typeof(audio_optio.Models.PaymentModel.State)).Cast<audio_optio.Models.PaymentModel.State>().Select(v => new SelectListItem
               {
                   Text = v.ToString(),
                   Value = v.ToString()
               }).ToList(), new { @class = "form-control" })
            </div>
            <div class="col-md-1"><label>Postal Code</label></div>
            <div class="col-md-2">
                @Html.TextBoxFor(model => model.contactOrder.order.BillingAddress.PostalCode, new { @class = "form-control" })
            </div>
        </div>
    </div>


    <hr />

    <div>
        <h2>Shipping Address</h2>
        @Html.CheckBoxFor(m => m.sameAddress, new { id = "same" })<span> <label>Same as Billing Address</label></span>

        <div id="shipping_address">
            <div class="row">
                <div class="col-md-3"><label>Name</label></div>
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.contactOrder.order.ShippingAddress.To, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <div class="col-md-3"><label>Address Line 1</label></div>
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.contactOrder.order.ShippingAddress.AddressLine1, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <div class="col-md-3"><label>Address Line 2</label></div>
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.contactOrder.order.ShippingAddress.AddressLine2, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <div class="col-md-2"><label>City</label></div>
                <div class="col-md-2">
                    @Html.TextBoxFor(model => model.contactOrder.order.ShippingAddress.City, new { @class = "form-control" })
                </div>
                <div class="col-md-2"><label>State</label></div>
                <div class="col-md-2">
                    @Html.DropDownListFor(model => model.contactOrder.order.ShippingAddress.State, EnumHelper.GetSelectList(typeof(audio_optio.Models.PaymentModel.State)),
   new { @class = "form-control" })
                </div>
                <div class="col-md-2"><label>Postal Code</label></div>
                <div class="col-md-2">
                    @Html.TextBoxFor(model => model.contactOrder.order.ShippingAddress.PostalCode, new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>


    <hr />

    <div class="wrapper">
        <div class="checkout container">
            <div class="row">
                <div class="col-sm-2">
                    <input class="form-control simple-checkbox animate-show-hide" id="agree" type="checkbox" checked="checked"/>
                </div>
                <div class="col-sm-5" id="agree-text">
                    <span>I agree to the <a data-toggle="modal" data-target="#toc">Terms and Conditions</a>.</span>
                </div>
            </div>
            <hr />
            <section id="bt-section">
                <div class="bt-drop-in-wrapper">
                    <div id="bt-dropin"></div>
                </div>
            </section>
            <input id="nonce" name="payment_method_nonce" type="hidden" />
            <button id="submit" class="button transition-button" type="submit"><span>Submit</span></button>
        </div>
    </div>
    
    <!-- Terms and Conditions -->
    <div class="modal fade" id="toc" tabindex="-1" role="dialog" aria-labelledby="toc" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title">Terms and Conditions</h1>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h4>Website Privacy Policy</h4>

                    <p>
                        This website privacy policy describes how Audio Optio protects and uses the information you provide the company when you order.
                        If you are asked to provide information when using this website, it will only be used in the ways described in this privacy policy.
                        This website privacy policy was updated on:	11/06/2017
                    </p>

                    <p>If you have any questions about this policy, please email  or write to: audio.optio@gmail.com</p>

                    <p>We collect data used for site analytics, shipping, and contact purposes only. This data includes:</p>
                    <ul>
                        <li>Name</li>
                        <li>Demographic information, such as postcode, preferences and interests</li>
                        <li>Website usage data</li>
                        <li>Phone Number</li>
                        <li>Email</li>
                        <li>Address</li>
                    </ul>

                    <p>The information is stored in a database owned by Azure. Security of this information is held to Azure's protective measures.</p>

                    <p>We will never lease, distribute, or sell your personal information to third parties unless we have your permission or the law requires us to.</p>

                    <hr />

                    <h4>Requesting a Reprint or Refund</h4>
                    <p>If you find any defect in your canvas such as loose or wavy canvas, bubbles, scratches, or fading, I will reprint or provide a 50% refund. Only a partial refund can be given due to the time spent creating the artwork.</p>

                    <p>
                        To request a reprint or refund please email <a href="mailto:audio.optio@gmail.com">audio.optio@gmail.com</a> with a digital image of the damage or defect along with a clear description of the problem.
                        The pictures will be reviewed within 48 hours and if found to have a manufacturing defect, the request will be granted.
                    </p>

                    <p>
                        <b>Request Window:</b> Customer can request a reprint or partial refund within 90 days from receipt of order.
                    </p>
                    <p>
                        <b>Refund Method:</b> The refund shall be issued on their card or PayPal from which order was paid for and is generally done within 7 business days.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" aria-label="Close">OK</button>
                </div>
            </div>
        </div>
    </div>
}
<script src="https://js.braintreegateway.com/web/dropin/1.8.0/js/dropin.min.js"></script>
<script>

    var client_token = "@ViewBag.ClientToken";
    var form = document.querySelector('#payment-form');

    braintree.dropin.create({
        authorization: client_token,
        container: '#bt-dropin',
        paypal: {
            //flow: 'vault'
            flow: 'checkout'
        }
    }, function (createErr, instance) {
        form.addEventListener('submit', function (event) {
            event.preventDefault();

            instance.requestPaymentMethod(function (err, payload) {
                if (err) {
                    console.log('Error', err);
                    return;
                }

                // Add the nonce to the form and submit
                document.querySelector('#nonce').value = payload.nonce;
                form.submit();
            });
        });
    });

</script>
<script>
    $(document).ready(function () {
        $("#agree").change(function () {
            if($(this).is(":checked"))
            {
                $("#bt-section, #submit").show();
                $("#agree-text").toggleClass("alert alert-danger");
            }
            else
            {
                $("#bt-section, #submit").hide();
                $("#agree-text").toggleClass("alert alert-danger");
            }
        });
    });
</script>
<script src="~/Scripts/PayViewToggle.js"></script>